services:
  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: shop_oracle_db
    environment:
      - ORACLE_PASSWORD=fwg4c8s
      - APP_USER=springshop
      - APP_USER_PASSWORD=fwg4c8s
      - ORACLE_DATABASE=shopdb
    ports:
      - "1521:1521"

  api:
    build: .
    container_name: shop_api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/shopdb
      - SPRING_DATASOURCE_USERNAME=springshop
      - SPRING_DATASOURCE_PASSWORD=fwg4c8s
    depends_on:
      - oracle-db
    restart: on-failure

volumes:
  oracle_data: