# DATASOURCE
spring.datasource.url=jdbc:oracle:thin:@//100.102.165.17:1521/XE
spring.datasource.username=springshop_api_database
spring.datasource.password=fwg4c8s
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=MYJWTSECRET
jwt.expiration=3600000